import { attach } from "./cdp.mjs";
const c = await attach();
const base = process.argv[2] || "http://localhost:8080";
const py = `Math.round(window.scrollY)`;
console.log("###### DatePicker: opening must not jump the page");
await c.go(base + "/c/datepicker");
await c.ev(`document.querySelectorAll('.p-datepicker input')[0].scrollIntoView({block:'center'}); 1`);
await c.sleep(400);
const before = await c.ev(py);
await c.click(".p-datepicker input");
await c.sleep(500);
const after = await c.ev(py);
console.log("scrollY", before, "->", after, await c.ev(`!!document.querySelector('.p-datepicker-panel, .p-datepicker-overlay')`));
console.log("###### Menubar: opening a submenu must not jump the page");
await c.go(base + "/c/menubar");
await c.ev(`document.querySelector('.p-menubar-root-list').scrollIntoView({block:'center'}); 1`);
await c.sleep(400);
const b2 = await c.ev(py);
await c.ev(`document.querySelector('.p-menubar-root-list').focus()`); await c.sleep(300);
await c.key("ArrowRight"); await c.key("ArrowDown");
const a2 = await c.ev(py);
console.log("scrollY", b2, "->", a2, await c.ev(`document.querySelectorAll('.p-menubar-submenu').length`));
c.close();
