package kyo.uic

import kyo.*

/** The PrimeOne theme for the uic components: generated design tokens
  * ([[generated.Tokens]], frozen from the MIT `@primeuix/themes` presets by
  * gen/extract.mjs) plus the per-component CSS ([[generated.ComponentCss]],
  * Prime's own `.p-*` stylesheets with `dt()` resolved to `var(--p-*)`) plus a
  * small kyo-specific remainder ([[primeExtraCss]]).
  *
  * Presets: Aura (default, on `:root`) / Material / Lara / Nora via a
  * `data-theme` attribute on any ancestor; dark scheme via `data-scheme="dark"`,
  * composable with every preset. Fonts: nothing is embedded — components
  * inherit the page font; the root rule prefers Inter with a system-ui
  * fallback, so self-hosting Inter is optional.
  *
  * Usage — SSG/SSR: `PageHead(css = uic.Theme.css)`; client mount: put
  * `uic.Theme.css` in the host page's `<style>`.
  */
object Theme:

    // === PrimeOne foundation (the target design system) ======================
    // Emitted as raw var-blocks (the values are machine-generated by gen/extract.mjs
    // from the MIT @primeuix engine's own output): `:root` carries the Aura light
    // set; the other presets are keyed by `data-theme` as override diffs against
    // Aura; the dark scheme is keyed by `data-scheme="dark"` and composes with any
    // preset. Component CSS (`.p-*`) consumes these vars and is preset-independent.

    private def varBlock(selector: String, pairs: Seq[(String, String)]): String =
        if pairs.isEmpty then ""
        else pairs.map((n, vl) => s"--$n:$vl").mkString(s"$selector{", ";", "}")

    private def presetDiff(preset: Seq[(String, String)], base: Map[String, String]): Seq[(String, String)] =
        preset.filterNot((n, vl) => base.get(n).contains(vl))

    /** All PrimeOne design tokens: Aura light on `:root`, presets + dark scheme scoped. */
    lazy val primeTokensCss: String =
        val auraLight = generated.Tokens.auraLight.toMap
        val presets = Seq(
            "material" -> (generated.Tokens.materialLight, generated.Tokens.materialDark),
            "lara"     -> (generated.Tokens.laraLight, generated.Tokens.laraDark),
            "nora"     -> (generated.Tokens.noraLight, generated.Tokens.noraDark)
        )
        // The Aura base set is re-declared on every theme/scheme scope (not just
        // `:root`): component tokens are var() chains (`--p-inputtext-background:
        // var(--p-form-field-background)`), and CSS substitutes var() at the element
        // that DECLARES the property — a `data-scheme="dark"` scope below `<html>`
        // only re-derives the chains if they are declared on the scope element too.
        val root = varBlock(""":root, [data-theme], [data-scheme]""", generated.Tokens.auraLight)
        val dark = varBlock("""[data-scheme="dark"]""", generated.Tokens.auraDark)
        val scoped = presets.flatMap { (name, sets) =>
            val (light, darkSet) = sets
            Seq(
                varBlock(s"""[data-theme="$name"]""", presetDiff(light, auraLight)),
                varBlock(s"""[data-theme="$name"][data-scheme="dark"]""", darkSet)
            )
        }
        (root +: dark +: scoped).filter(_.nonEmpty).mkString("\n")
    end primeTokensCss

    /** The PrimeOne layer: tokens + base/component CSS + the inherited page font
      * (Prime sets no font-family of its own; the showcase look is Inter) + the
      * kyo-specific remainder ([[primeExtraCss]]).
      */
    lazy val primeCss: String =
        primeTokensCss + "\n" +
            ":root{font-family:Inter,system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif}\n" +
            generated.ComponentCss.all + "\n" + primeExtraCss

    /** The kyo-specific PrimeOne remainder (`.p-uic-*` plus pieces Prime implements
      * in JS or slots rather than component CSS): the Button loading spinner
      * animation, the `invalidMessage` row, Label (Prime ships no label CSS),
      * TextArea autoResize via CSS `field-sizing`, the label wrapper of
      * CheckBox/RadioButton text, displayOnly, and the ToggleSwitch root
      * positioning PrimeVue applies as an inline style.
      */
    val primeExtraCss: String =
        """@keyframes p-icon-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      |.p-icon-spin { animation: p-icon-spin 2s linear infinite; }
      |.p-uic-invalid-message { color: var(--p-form-field-invalid-placeholder-color, #ef4444); font-size: 0.875rem; margin-top: 0.25rem; }
      |.p-uic-label { display: inline-flex; align-items: baseline; }
      |.p-uic-label-required::after { content: "*"; color: var(--p-form-field-invalid-border-color, #ef4444); margin-inline-start: 0.125rem; }
      |.p-uic-label-colon::after { content: ":"; }
      |.p-uic-autoresize { field-sizing: content; }
      |.p-uic-control-label { display: inline-flex; flex-direction: row; align-items: center; gap: 0.5rem; cursor: pointer; }
      |.p-uic-display-only, .p-uic-display-only * { cursor: default; pointer-events: none; }
      |/* aria-disabled button: greyed like :disabled but STILL focusable + clickable (pointer-events
      |   stays on) so the click can route through form.submit → focus-first-invalid. */
      |.p-uic-aria-disabled { opacity: var(--p-disabled-opacity, 0.6); cursor: not-allowed; }
      |/* PrimeVue sets this via ToggleSwitchStyle.inlineStyles — the extracted component CSS lacks it. */
      |.p-toggleswitch { position: relative; }
      |/* GlyphSvg renders <span class="..."><svg/></span>; Prime sizes the icon element
      |   itself, so spans sized by the component CSS scale their inner svg with them. */
      |span.p-checkbox-icon, span.p-message-icon, span.p-message-close-icon,
      |span.p-tag-icon, span.p-avatar-icon { display: inline-flex; align-items: center; justify-content: center; }
      |span.p-checkbox-icon > svg, span.p-message-icon > svg, span.p-message-close-icon > svg,
      |span.p-tag-icon > svg, span.p-avatar-icon > svg { width: 100%; height: 100%; }
      |/* Icon (p-uic-icon): the span hugs its svg — the svg carries the size, overriding
      |   .p-icon's 1rem default box. */
      |.p-uic-icon { display: inline-flex; align-items: center; justify-content: center; width: auto; height: auto; }
      |/* kyo-ui's base CSS defaults every div to a COLUMN flexbox; Prime's component
      |   CSS relies on the browser's row default and never declares flex-direction —
      |   restore row on the flex containers the wave-B/C components depend on. */
      |.p-message-content, .p-toolbar, .p-toolbar-start, .p-toolbar-center, .p-toolbar-end,
      |.p-panel-header, .p-tablist, .p-tablist-tab-list, .p-breadcrumb-list,
      |div.p-tree-node-content { flex-direction: row; }
      |/* kyo-ui's li default is a centered row flexbox; a tree node stacks its
      |   content row above the nested child list. */
      |li.p-tree-node { flex-direction: column; align-items: stretch; }
      |/* The selection click lives on the label (toggle clicks must not select);
      |   stretching it keeps the whole free row width clickable. */
      |.p-tree-node-label { flex: 1 1 auto; }
      |/* Link (kyo extension — Prime has no Link component; skin mirrors Button's
      |   Link variant: primary color, underline on hover, disabled via .p-disabled). */
      |.p-uic-link { color: var(--p-primary-color); cursor: pointer; text-decoration: none; gap: 0.25rem; white-space: nowrap; }
      |.p-uic-link:not(.p-disabled):hover { text-decoration: underline; }
      |.p-uic-link-wrap { white-space: normal; overflow-wrap: anywhere; }
      |/* Click-handler wrapper that must not affect layout (Breadcrumb item links). */
      |.p-uic-link-wrapper { display: contents; }
      |/* Listbox option extensions: leading icon + right-aligned additional text. */
      |.p-uic-option-icon { margin-inline-end: 0.5rem; flex-shrink: 0; }
      |.p-uic-option-extra { margin-inline-start: auto; padding-inline-start: 0.75rem; color: var(--p-text-muted-color); font-size: 0.875rem; white-space: nowrap; }
      |/* Tabs: count badge (kyo extension) + the ink bar, which Prime positions via
      |   JS measuring — here it sits inside the active tab and spans it. */
      |.p-uic-tab-count { font-size: 0.75rem; line-height: 1.25; padding: 0 0.375rem; border-radius: 0.625rem; background: var(--p-primary-color); color: var(--p-primary-contrast-color); }
      |.p-tab > .p-tablist-active-bar { inset-inline: 0; }
      |/* Shared hook for kyo onClick extensions on inert Prime components (Tag, Avatar). */
      |.p-uic-clickable { cursor: pointer; }
      |/* Avatar badge overlay (kyo extension; Prime's OverlayBadge arrives later). */
      |.p-avatar:has(.p-uic-avatar-badge) { position: relative; }
      |.p-uic-avatar-badge {
      |  position: absolute; inset-block-end: 0; inset-inline-end: 0;
      |  display: flex; align-items: center; justify-content: center;
      |  min-width: 1.125rem; height: 1.125rem; padding: 0 0.25rem; box-sizing: border-box;
      |  border-radius: 0.5625rem; background: var(--p-primary-color);
      |  color: var(--p-primary-contrast-color);
      |  border: 0.0625rem solid var(--p-content-background);
      |  font-size: 0.625rem; line-height: 1; pointer-events: none;
      |}
      |/* Card caption row: kyo's avatar/action/additionalText extensions flank Prime's caption. */
      |.p-uic-card-caption-row { display: flex; flex-direction: row; align-items: center; gap: 0.75rem; }
      |.p-uic-card-caption-row .p-card-caption { flex: 1 1 auto; min-width: 0; }
      |.p-uic-card-avatar, .p-uic-card-action { flex-shrink: 0; }
      |.p-uic-card-additional {
      |  flex-shrink: 0; margin-inline-start: auto; align-self: flex-start;
      |  color: var(--p-card-subtitle-color); font-size: 0.875rem;
      |}
      |.p-uic-card-caption-row--interactive { cursor: pointer; }
      |/* Panel header actions: the extracted panel CSS lacks this container rule. */
      |.p-panel-header-actions { display: flex; align-items: center; gap: 0.25rem; }
      |/* Title/Text: Prime ships no typographic primitives — rem scale, Inter inherits. */
      |.p-uic-title { color: var(--p-text-color); font-weight: 600; margin: 0; }
      |.p-uic-title--h1 { font-size: 2rem; }
      |.p-uic-title--h2 { font-size: 1.5rem; }
      |.p-uic-title--h3 { font-size: 1.25rem; }
      |.p-uic-title--h4 { font-size: 1.125rem; }
      |.p-uic-title--h5 { font-size: 1rem; }
      |.p-uic-title--h6 { font-size: 0.875rem; }
      |.p-uic-title--nowrap { white-space: nowrap; }
      |.p-uic-text { color: var(--p-text-color); margin: 0; }
      |.p-uic-text--clamp { display: -webkit-box; -webkit-box-orient: vertical; overflow: hidden; }
      |.p-uic-text--empty-indicator:empty::before { content: "–"; color: var(--p-text-muted-color); }
      |/* ProgressSpinner size presets (Prime sizes the spinner via an inline style). */
      |.p-uic-progressspinner-sm { width: 2rem; height: 2rem; }
      |.p-uic-progressspinner-lg { width: 8rem; height: 8rem; }
      |/* FlexBox (kyo layout primitive — Prime ships none). */
      |.p-uic-flex { display: flex; }
      |.p-uic-flex--wrap-reverse { flex-wrap: wrap-reverse; }
      |.p-uic-flex--fit { width: 100%; height: 100%; }
      |/* ==== wave D ==== */
      |/* Row restorers (kyo base CSS: every div is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). */
      |.p-select, .p-datepicker, .p-datepicker-header, .p-datepicker-title,
      |.p-datepicker-calendar-container, .p-dialog-header, .p-dialog-header-actions,
      |.p-dialog-footer, .p-toast-message-content, .p-datatable-column-header-content,
      |.p-paginator { flex-direction: row; }
      |/* Select: the trigger is Prime's div anatomy (span label + chevron); the
      |   readonly remainder keeps the non-dimmed look while interaction is off. */
      |.p-uic-select-readonly { cursor: default; }
      |.p-select { align-items: stretch; }
      |/* AutoComplete: row restorer (kyo's div column default) + the overlay
      |   anchor position; the floating panel geometry itself comes from the
      |   Overlay primitive (wave J). */
      |.p-autocomplete { flex-direction: row; align-items: stretch; position: relative; }
      |/* DatePicker: wrap the row so the INLINE panel variant (min-width 100%
      |   from the extracted CSS) drops under the input + dropdown button. */
      |.p-datepicker { flex-wrap: wrap; }
      |.p-datepicker-panel-inline { margin-block-start: 0.25rem; }
      |.p-datepicker-day-view th { text-align: center; }
      |/* Dialog: Prime centers the mask and stacks the box via inline styles —
      |   expressed as CSS here. */
      |.p-dialog-mask { display: flex; flex-direction: row; align-items: center; justify-content: center; z-index: 1200; }
      |.p-dialog { display: flex; flex-direction: column; min-width: 20rem; }
      |/* Dialog severity accent (kyo extension): subtle colored border under the
      |   header + tinted leading icon. */
      |.p-uic-dialog-severity-icon { display: inline-flex; margin-inline-end: 0.5rem; }
      |/* Toast: Prime pins the region via inline styles — expressed per position
      |   token here (the center tokens pair with the extracted transform rules). */
      |.p-toast { position: fixed; z-index: 1300; }
      |.p-toast-top-left { top: 20px; left: 20px; }
      |.p-toast-top-center { top: 20px; left: 50%; }
      |.p-toast-top-right { top: 20px; right: 20px; }
      |.p-toast-bottom-left { bottom: 20px; left: 20px; }
      |.p-toast-bottom-center { bottom: 20px; left: 50%; }
      |.p-toast-bottom-right { bottom: 20px; right: 20px; }
      |.p-toast-center { top: 50%; left: 50%; }
      |/* DataTable: kyo-ui has no <thead>/<tbody> factories, so the thead/tbody-
      |   scoped Prime rules are re-expressed against the row classes the component
      |   stamps (.p-uic-dt-header-row / .p-uic-dt-row). */
      |.p-datatable-table tr.p-uic-dt-row, .p-datatable-table tr.p-datatable-empty-message, .p-datatable-table tr.p-datatable-row-expansion {
      |  background: var(--p-datatable-row-background); color: var(--p-datatable-row-color);
      |}
      |.p-datatable-table tr > td {
      |  text-align: start; padding: var(--p-datatable-body-cell-padding);
      |  border-color: var(--p-datatable-body-cell-border-color); border-style: solid; border-width: 0 0 1px 0;
      |}
      |.p-datatable-hoverable tr.p-uic-dt-row:not(.p-datatable-row-selected):hover {
      |  background: var(--p-datatable-row-hover-background); color: var(--p-datatable-row-hover-color);
      |}
      |.p-datatable-table tr.p-datatable-row-selected {
      |  background: var(--p-datatable-row-selected-background); color: var(--p-datatable-row-selected-color);
      |}
      |.p-datatable-striped tr.p-uic-dt-row.p-row-odd { background: var(--p-datatable-row-striped-background); }
      |.p-datatable-striped tr.p-uic-dt-row.p-row-odd.p-datatable-row-selected {
      |  background: var(--p-datatable-row-selected-background); color: var(--p-datatable-row-selected-color);
      |}
      |.p-datatable-gridlines th.p-datatable-header-cell { border-width: 1px 0 1px 1px; }
      |.p-datatable-gridlines th.p-datatable-header-cell:last-child { border-width: 1px; }
      |.p-datatable-gridlines .p-datatable-table tr > td { border-width: 0 0 1px 1px; }
      |.p-datatable-gridlines .p-datatable-table tr > td:last-child { border-width: 0 1px 1px 1px; }
      |.p-datatable-sm th.p-datatable-header-cell { padding: var(--p-datatable-header-cell-sm-padding); }
      |.p-datatable-sm .p-datatable-table tr > td { padding: var(--p-datatable-body-cell-sm-padding); }
      |.p-datatable-lg th.p-datatable-header-cell { padding: var(--p-datatable-header-cell-lg-padding); }
      |.p-datatable-lg .p-datatable-table tr > td { padding: var(--p-datatable-body-cell-lg-padding); }
      |.p-datatable-table tr.p-datatable-empty-message > td { text-align: center; color: var(--p-text-muted-color); }
      |.p-datatable-table tr.p-datatable-row-expansion > td { background: var(--p-content-hover-background); }
      |/* GlyphSvg spans sized by the extracted component CSS scale their inner svg
      |   (wave-D additions to the wave-B/C list above). */
      |span.p-select-dropdown-icon, span.p-toast-message-icon, span.p-toast-close-icon,
      |span.p-datatable-sort-icon, span.p-datatable-row-toggle-icon,
      |span.p-paginator-first-icon, span.p-paginator-prev-icon,
      |span.p-paginator-next-icon, span.p-paginator-last-icon {
      |  display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0;
      |}
      |span.p-select-dropdown-icon > svg, span.p-toast-message-icon > svg, span.p-toast-close-icon > svg,
      |span.p-datatable-sort-icon > svg, span.p-datatable-row-toggle-icon > svg,
      |span.p-paginator-first-icon > svg, span.p-paginator-prev-icon > svg,
      |span.p-paginator-next-icon > svg, span.p-paginator-last-icon > svg { width: 100%; height: 100%; }
      |/* Column alignment helpers (Prime aligns via per-column styles). */
      |.p-uic-dt-center { text-align: center; }
      |.p-uic-dt-center > .p-datatable-column-header-content { justify-content: center; }
      |.p-uic-dt-end { text-align: end; }
      |.p-uic-dt-end > .p-datatable-column-header-content { justify-content: flex-end; }
      |/* ==== wave E ==== */
      |/* Row restorers (kyo base CSS: every div/ol is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). */
      |.p-divider-horizontal, .p-divider-vertical, .p-avatar-group, .p-chip,
      |.p-metergroup-meters, ol.p-metergroup-label-list { flex-direction: row; }
      |/* Skeleton: PrimeVue sets this via SkeletonStyle.inlineStyles — the ::after
      |   shimmer is absolutely positioned against the root. */
      |.p-skeleton { position: relative; }
      |/* OverlayBadge: Prime relies on a plain block div; kyo's column-flex div
      |   default would stretch the child and misplace the corner badge — an
      |   inline-flex row hugs the single wrapped child instead. */
      |.p-overlaybadge { display: inline-flex; flex-direction: row; }
      |/* Chip remove affordance renders as a real <button> around the glyph (Prime
      |   uses a bare svg with handlers) — strip the native button chrome; the
      |   extracted .p-chip-remove-icon rules size and color it. */
      |button.p-chip-remove-icon { background: transparent; border: 0 none; padding: 0; flex-shrink: 0; justify-content: center; }
      |/* GlyphSvg spans sized by the extracted component CSS scale their inner svg
      |   (wave-E additions to the wave-B/C/D lists above). */
      |span.p-chip-icon { display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; }
      |span.p-chip-icon > svg, button.p-chip-remove-icon svg { width: 100%; height: 100%; }
      |/* Fieldset toggle button: the extracted CSS strips chrome and lays it out,
      |   but the UA button font/color do not inherit on their own. */
      |button.p-fieldset-toggle-button { font: inherit; color: inherit; }
      |/* ScrollPanel (server-honest deferral): Prime hides the native scrollbars and
      |   drives custom .p-scrollpanel-bar elements from JS scroll measuring — with
      |   no JS lifecycle server-side, scroll NATIVELY instead: re-enable the native
      |   scrollbars and style them thin with the scrollpanel bar tokens. */
      |.p-scrollpanel .p-scrollpanel-content {
      |  width: 100%; height: 100%; padding: 0;
      |  scrollbar-width: thin;
      |  scrollbar-color: var(--p-scrollpanel-bar-background) transparent;
      |}
      |.p-scrollpanel .p-scrollpanel-content::-webkit-scrollbar { display: block; width: 9px; height: 9px; }
      |.p-scrollpanel .p-scrollpanel-content::-webkit-scrollbar-thumb { background: var(--p-scrollpanel-bar-background); border-radius: var(--p-scrollpanel-bar-border-radius); }
      |.p-scrollpanel .p-scrollpanel-content::-webkit-scrollbar-track { background: transparent; }
      |/* ==== wave F ==== */
      |/* Row restorers (kyo base CSS: every div is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). The
      |   layout-variant rules (.p-timeline-horizontal .p-timeline-event, ...) keep
      |   winning on specificity. */
      |.p-rating, .p-rating-option, .p-selectbutton, .p-inputgroup,
      |.p-timeline-event, .p-steplist, .p-step { flex-direction: row; }
      |/* GlyphSvg spans sized by the extracted component CSS scale their inner svg
      |   (wave-F additions to the wave-B/C/D/E lists above). */
      |span.p-rating-icon, span.p-togglebutton-icon {
      |  display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0;
      |}
      |span.p-rating-icon > svg { width: 100%; height: 100%; }
      |/* InputIcon: Prime sizes the font icon via font-size; the glyph span gets
      |   the token box so the iconfield padding/centering math holds. */
      |span.p-inputicon {
      |  display: inline-flex; align-items: center; justify-content: center;
      |  width: var(--p-icon-size, 1rem); height: var(--p-icon-size, 1rem);
      |}
      |span.p-inputicon > svg { width: 100%; height: 100%; }
      |/* Stepper header: the extracted CSS strips chrome and lays it out, but the
      |   UA button font does not inherit on its own (the Fieldset toggle lesson). */
      |button.p-step-header { font: inherit; }
      |/* Steppanel is a plain block in Prime; kyo's column flexbox would stretch
      |   buttons/fields in the panel content to full width. */
      |.p-steppanel { display: block; }
      |/* Two-way bound kyo fields render inside a classless reactive <span> — the
      |   kyo analogue of Prime's .p-inputwrapper. Mirror the inputwrapper rules on
      |   it so InputGroup keeps fusing radii and stretching the field. */
      |.p-inputgroup > span[data-kyo-reactive] { display: inline-flex; flex: 1 1 auto; width: 1%; }
      |.p-inputgroup > span[data-kyo-reactive] > .p-component { border-radius: 0; margin: 0; flex: 1 1 auto; width: 100%; }
      |.p-inputgroupaddon:first-child, .p-inputgroup > span[data-kyo-reactive]:first-child > .p-component {
      |  border-start-start-radius: var(--p-inputgroup-addon-border-radius);
      |  border-end-start-radius: var(--p-inputgroup-addon-border-radius);
      |}
      |.p-inputgroupaddon:last-child, .p-inputgroup > span[data-kyo-reactive]:last-child > .p-component {
      |  border-start-end-radius: var(--p-inputgroup-addon-border-radius);
      |  border-end-end-radius: var(--p-inputgroup-addon-border-radius);
      |}
      |/* IconField pads the input via sibling-position selectors in Prime; the kyo
      |   reactive wrapper resets sibling positions, so IconField stamps these
      |   classes deterministically (same padding calc as the extracted rules). */
      |.p-iconfield .p-inputtext.p-uic-iconfield-start { padding-inline-start: calc((var(--p-form-field-padding-x) * 2) + var(--p-icon-size)); }
      |.p-iconfield .p-inputtext.p-uic-iconfield-end { padding-inline-end: calc((var(--p-form-field-padding-x) * 2) + var(--p-icon-size)); }
      |/* ==== wave G ==== */
      |/* Row restorers (kyo base CSS: every div is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). */
      |.p-datepicker-buttonbar, .p-datepicker-time-picker,
      |.p-steppanel-content-wrapper { flex-direction: row; }
      |/* DatePicker month/year grids: Prime relies on BLOCK containers wrapping
      |   their inline-flex percent-width cells; kyo's column-flex div default
      |   would stack them full-width instead. */
      |.p-datepicker-month-view, .p-datepicker-year-view { display: block; }
      |/* DatePicker title/select buttons: the extracted CSS strips chrome, but
      |   the UA button font does not inherit on its own (the Fieldset toggle
      |   lesson). */
      |button.p-datepicker-select-month, button.p-datepicker-select-year { font: inherit; }
      |/* Vertical stepper panel content is a plain block in Prime; kyo's column
      |   flexbox would stretch buttons/fields in the panel to full width. */
      |.p-steppanel-content { display: block; }
      |/* MeterGroup vertical label list: the wave-E `ol.p-metergroup-label-list`
      |   row restorer above outweighs Prime's single-class vertical rule — re-
      |   declare the column at matching specificity after it. */
      |ol.p-metergroup-label-list-vertical { flex-direction: column; }
      |/* ==== wave H ==== */
      |/* Prime's base visually-hidden helper (Rating's hidden per-option radios):
      |   injected by Prime's styled engine at runtime, not the extracted
      |   per-component sheets — values byte-match the live PrimeVue 4.5 rule. */
      |.p-hidden-accessible {
      |  border: 0; clip: rect(0 0 0 0); height: 1px; margin: -1px; opacity: 0;
      |  overflow: hidden; padding: 0; pointer-events: none; position: absolute;
      |  white-space: nowrap; width: 1px;
      |}
      |/* IconField hosts beyond Input (kyo extension — Prime's sheet only pads
      |   .p-inputtext): same padding calc for TextArea and the native Select. */
      |.p-iconfield .p-textarea.p-uic-iconfield-start { padding-inline-start: calc((var(--p-form-field-padding-x) * 2) + var(--p-icon-size)); }
      |.p-iconfield .p-textarea.p-uic-iconfield-end { padding-inline-end: calc((var(--p-form-field-padding-x) * 2) + var(--p-icon-size)); }
      |.p-iconfield .p-select.p-uic-iconfield-start .p-select-label { padding-inline-start: calc((var(--p-form-field-padding-x) * 2) + var(--p-icon-size)); }
      |.p-iconfield .p-select.p-uic-iconfield-end .p-select-label { padding-inline-end: calc((var(--p-form-field-padding-x) * 2) + var(--p-icon-size)); }
      |/* FloatLabel on Select: the sheet floats wrapped fields via the JS-stamped
      |   .p-inputwrapper-focus — mirror the focus float with :focus-within on the
      |   div trigger (tabindex="0"; the open panel lives inside the root, so the
      |   float holds while the panel is open) using the sheet's active values. */
      |.p-floatlabel:has(.p-select:focus-within) label {
      |  top: var(--p-floatlabel-over-active-top);
      |  transform: translateY(0);
      |  font-size: var(--p-floatlabel-active-font-size);
      |  font-weight: var(--p-floatlabel-active-font-weight);
      |  color: var(--p-floatlabel-focus-color);
      |}
      |.p-floatlabel-in:has(.p-select:focus-within) label { top: var(--p-floatlabel-in-active-top); }
      |.p-floatlabel-on:has(.p-select:focus-within) label {
      |  top: 0;
      |  transform: translateY(-50%);
      |  border-radius: var(--p-floatlabel-on-border-radius);
      |  background: var(--p-floatlabel-on-active-background);
      |  padding: var(--p-floatlabel-on-active-padding);
      |}
      |/* ToggleSwitch handle slot: size the glyph below the handle box (PrimeVue's
      |   showcase styles the slotted icon down to 0.75rem itself). */
      |span.p-uic-toggleswitch-handle-icon {
      |  display: inline-flex; align-items: center; justify-content: center;
      |  width: 0.75rem; height: 0.75rem;
      |}
      |span.p-uic-toggleswitch-handle-icon > svg { width: 100%; height: 100%; }
      |/* DataView loading: PrimeReact anchors the absolute overlay on the root via
      |   its root modifier — the extracted sheet ships only the overlay rule. */
      |.p-dataview-loading { position: relative; min-height: 4rem; }
      |/* ==== wave I: Overlay primitive + Select floating panel ==== */
      |/* Overlay (kyo primitive): anchor glue + backdrop/panel geometry. The anchor
      |   element must be position:relative — stamp .p-uic-overlay-anchor on it.
      |   z-index: non-modal overlays sit at 1000/1001 (Prime's overlay layer),
      |   below the Dialog mask (1200) and Toast (1300); an overlay INSIDE a
      |   dialog still paints above the mask because it lives in the dialog's
      |   stacking context. */
      |.p-uic-overlay-anchor { position: relative; }
      |.p-uic-overlay-backdrop { position: fixed; inset: 0; z-index: 1000; background: transparent; }
      |/* Block, not kyo's div column-flex default: Prime panels are blocks (byte-
      |   compared), and block children stack the same way. cursor resets to auto
      |   so an anchor's pointer (Prime's .p-select trigger) does not leak in. */
      |.p-uic-overlay-panel { position: absolute; z-index: 1001; display: block; cursor: auto; }
      |/* The panel is a tabindex="-1" focus-seed target — no native ring on it. */
      |.p-uic-overlay-panel:focus { outline: none; }
      |/* Prime's overlay gutter: 2px between anchor and panel (byte-compared
      |   against the live PrimeVue select overlay). */
      |.p-uic-overlay-bottom-start { top: 100%; bottom: auto; left: 0; right: auto; margin-top: 2px; }
      |.p-uic-overlay-bottom-end { top: 100%; bottom: auto; left: auto; right: 0; margin-top: 2px; }
      |.p-uic-overlay-top-start { bottom: 100%; top: auto; left: 0; right: auto; margin-bottom: 2px; }
      |.p-uic-overlay-top-end { bottom: 100%; top: auto; left: auto; right: 0; margin-bottom: 2px; }
      |.p-uic-overlay-match-width { min-width: 100%; }
      |/* Portal mode (Overlay.portal(true)): the panel re-homes to document.body (fork
      |   portal) and is placed with measured FIXED viewport coordinates patched in
      |   place. position:fixed overrides the anchor classes' absolute geometry (two
      |   classes beat one); opacity:0 gates the unmeasured first paint — the first
      |   geometry patch sets opacity:1 inline. The probe is an inset-0 child of the
      |   anchor that stands in for it as a measurable, id-addressed box. */
      |.p-uic-overlay-panel.p-uic-overlay-portal { position: fixed; opacity: 0; }
      |.p-uic-overlay-anchor-probe { position: absolute; inset: 0; pointer-events: none; visibility: hidden; }
      |/* Prime's select header/list container are blocks (kyo base CSS would make
      |   these divs column flexboxes). */
      |.p-select-overlay .p-select-list-container, .p-select-overlay .p-select-header { display: block; }
      |/* Select focus ring: Prime stamps .p-focus from JS — map the ring onto
      |   native :focus-within (the trigger root carries tabindex="0"; the open
      |   panel also lives inside the root, so the ring holds while open, exactly
      |   Prime's open-field look). */
      |.p-select:not(.p-disabled):focus-within {
      |  border-color: var(--p-select-focus-border-color);
      |  box-shadow: var(--p-select-focus-ring-shadow);
      |  outline: var(--p-select-focus-ring-width) var(--p-select-focus-ring-style) var(--p-select-focus-ring-color);
      |  outline-offset: var(--p-select-focus-ring-offset);
      |}
      |/* Prime caps the option list via the scrollHeight prop (default 14rem) as
      |   an inline style on the list container; expressed as CSS here. */
      |.p-select-overlay .p-select-list-container { max-height: 14rem; }
      |/* The clear affordance is a real <button> (Prime uses a bare svg with
      |   handlers) — strip the native chrome; the extracted .p-select-clear-icon
      |   rule colors it. It sits as a flex sibling between label and chevron. */
      |button.p-select-clear-icon { background: transparent; border: 0 none; padding: 0; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; }
      |/* GlyphSvg spans sized by the extracted component CSS scale their inner svg
      |   (wave-I additions to the earlier lists). */
      |span.p-select-option-check-icon, span.p-select-option-blank-icon {
      |  display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0;
      |}
      |span.p-select-option-check-icon > svg, button.p-select-clear-icon svg { width: 100%; height: 100%; }
      |/* ==== wave J: Tooltip + Popover + AutoComplete/DatePicker floating panels ==== */
      |/* Tooltip (CSS-driven deviation): Prime's directive mounts/positions the box
      |   from JS — here the box is always in the DOM (the sheet ships display:none)
      |   and the relative wrapper's :hover/:focus-within shows it. width:max-content
      |   frees the box from the wrapper's shrink-to-fit width; pointer-events:none
      |   matches Prime's autoHide default (the box is not interactive). z-index
      |   1100 = Prime's tooltip layer (above overlays at 1000/1001). */
      |.p-uic-tooltip { position: relative; display: inline-flex; flex-direction: row; }
      |.p-uic-tooltip > .p-tooltip { z-index: 1100; width: max-content; pointer-events: none; }
      |.p-uic-tooltip:hover > .p-tooltip, .p-uic-tooltip:focus-within > .p-tooltip { display: block; }
      |/* Box placement per positional class (Prime computes these from JS measuring;
      |   the sheet's gutter padding keeps the arrow gap). */
      |.p-uic-tooltip > .p-tooltip-top { bottom: 100%; left: 50%; transform: translateX(-50%); }
      |.p-uic-tooltip > .p-tooltip-bottom { top: 100%; left: 50%; transform: translateX(-50%); }
      |.p-uic-tooltip > .p-tooltip-right { left: 100%; top: 50%; transform: translateY(-50%); }
      |.p-uic-tooltip > .p-tooltip-left { right: 100%; top: 50%; transform: translateY(-50%); }
      |/* Arrow placement (Prime sets these as inline styles; the sheet's border
      |   triangles + margin offsets center it against the placements above). */
      |.p-tooltip-top .p-tooltip-arrow { bottom: 0; left: 50%; }
      |.p-tooltip-bottom .p-tooltip-arrow { top: 0; left: 50%; }
      |.p-tooltip-right .p-tooltip-arrow { left: 0; top: 50%; }
      |.p-tooltip-left .p-tooltip-arrow { right: 0; top: 50%; }
      |/* Popover: the sheet's :before/:after arrow reads --p-popover-arrow-left,
      |   which Prime sets from JS pointer measuring — fix it at 0 (the arrow sits
      |   at the token offset from the panel's start edge). The panel margin
      |   restores the sheet's arrow gutter over the Overlay geometry's 2px. */
      |.p-popover { --p-popover-arrow-left: 0px; }
      |.p-uic-overlay-panel.p-popover { margin-top: var(--p-popover-gutter); }
      |.p-uic-overlay-panel.p-popover.p-popover-flipped { margin-top: 0; margin-bottom: var(--p-popover-gutter); }
      |/* The trigger wrapper hugs its child inside the anchor (kyo div default
      |   would stretch it column-wise). */
      |.p-uic-popover-anchor { display: inline-flex; flex-direction: row; }
      |.p-uic-popover-trigger { display: inline-flex; }
      |/* AutoComplete floating panel: the two-way bound field renders inside kyo's
      |   classless reactive <span> — size it like the input flex item the sheet
      |   expects; the list container is a block capped at Prime's scrollHeight
      |   default (14rem, an inline style in Prime). */
      |.p-autocomplete > span[data-kyo-reactive] { display: inline-flex; flex: 1 1 auto; }
      |.p-autocomplete > span[data-kyo-reactive] > .p-autocomplete-input { flex: 1 1 auto; width: 100%; }
      |.p-autocomplete-overlay .p-autocomplete-list-container { display: block; max-height: 14rem; }
      |/* The loader/clear affordances are positioned by the extracted sheet
      |   (.p-autocomplete-loader / .p-autocomplete-clear-icon); the glyph spans
      |   need the flex centering, the clear <button> its chrome stripped. */
      |span.p-autocomplete-loader { display: inline-flex; align-items: center; justify-content: center; }
      |button.p-autocomplete-clear-icon { background: transparent; border: 0 none; padding: 0; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; }
      |span.p-autocomplete-loader > svg, button.p-autocomplete-clear-icon svg { width: 100%; height: 100%; }
      |/* The dropdown trigger is a real <button>; the sheet skins it but the UA
      |   font/color do not inherit on their own (the Fieldset toggle lesson). */
      |button.p-autocomplete-dropdown { font: inherit; }
      |/* ==== wave K: menu family (Menu/Menubar/TieredMenu/MegaMenu/SplitButton/SpeedDial) ==== */
      |/* Overlay side placements (Prime's nested-submenu geometry: the panel sits
      |   beside its anchor, top-aligned — the sheet's `left: 100%; top: 0`). */
      |.p-uic-overlay-right-start { top: 0; bottom: auto; left: 100%; right: auto; }
      |.p-uic-overlay-left-start { top: 0; bottom: auto; right: 100%; left: auto; }
      |/* Row restorers (kyo base CSS: every div/ul is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). The
      |   vertical-variant sheet rules (.p-megamenu-vertical .p-megamenu-root-list)
      |   keep winning on specificity. */
      |.p-menubar, ul.p-menubar-root-list, ul.p-megamenu-root-list,
      |.p-megamenu-grid, .p-splitbutton,
      |a.p-menu-item-link, a.p-menubar-item-link, a.p-tieredmenu-item-link,
      |a.p-megamenu-item-link { flex-direction: row; }
      |/* kyo's li default is a centered row flexbox; a menu row stacks its content
      |   block full-width (the tree-node lesson). */
      |li.p-menu-item, li.p-menubar-item, li.p-tieredmenu-item, li.p-megamenu-item,
      |li.p-menu-submenu-label, li.p-megamenu-submenu-label { flex-direction: column; align-items: stretch; }
      |/* Submenu panels ride the Overlay primitive; the panel geometry class sets
      |   display:block — restore the sheet's flex column (menubar) and kill the
      |   overlay gutter (Prime nested submenus sit flush: left:100%/top:100%). */
      |.p-uic-overlay-panel.p-menubar-submenu, .p-uic-overlay-panel.p-tieredmenu-submenu {
      |  display: flex; flex-direction: column; margin: 0;
      |}
      |/* The rows ride inside a real <ul> (the HTML parser closes an open <li>
      |   when it meets a new <li> even across a <div> panel) — lay the li's out
      |   as if they were the panel's direct children. */
      |ul.p-uic-submenu-list { display: contents; }
      |.p-uic-overlay-panel.p-megamenu-overlay { margin: 0; }
      |/* The tieredmenu popup sheet's JS-era will-change:transform would make the
      |   panel the containing block for the nested submenus' position:fixed
      |   backdrops — neutralize it (perf hint only, zero visual effect). */
      |.p-uic-overlay-panel.p-tieredmenu-overlay { will-change: auto; }
      |/* GlyphSvg spans sized by the extracted component CSS scale their inner svg
      |   (wave-K additions to the earlier lists). */
      |span.p-menubar-submenu-icon, span.p-tieredmenu-submenu-icon, span.p-megamenu-submenu-icon {
      |  display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0;
      |}
      |span.p-menubar-submenu-icon > svg, span.p-tieredmenu-submenu-icon > svg,
      |span.p-megamenu-submenu-icon > svg { width: 100%; height: 100%; }
      |/* SpeedDial linear directions: Prime lays these out via
      |   SpeedDialStyle.inlineStyles — expressed as CSS here (ToggleSwitch
      |   precedent). */
      |.p-speeddial-up { flex-direction: column-reverse; align-items: center; }
      |.p-speeddial-up .p-speeddial-list { flex-direction: column-reverse; }
      |.p-speeddial-down { flex-direction: column; align-items: center; }
      |.p-speeddial-down .p-speeddial-list { flex-direction: column; }
      |.p-speeddial-left { flex-direction: row-reverse; }
      |.p-speeddial-left .p-speeddial-list { flex-direction: row-reverse; }
      |.p-speeddial-right { flex-direction: row; }
      |.p-speeddial-right .p-speeddial-list { flex-direction: row; }
      |/* ==== wave L: MultiSelect / CascadeSelect / TreeSelect / Drawer ==== */
      |/* Row restorers (kyo base CSS: every div is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). */
      |.p-multiselect, .p-cascadeselect, .p-treeselect,
      |.p-multiselect-header, .p-drawer-header,
      |div.p-cascadeselect-option-content, .p-treeselect-label,
      |.p-multiselect-display-chip .p-multiselect-label { flex-direction: row; }
      |.p-multiselect, .p-cascadeselect, .p-treeselect { align-items: stretch; }
      |/* Trigger label containers are plain blocks in Prime (the label div fills). */
      |.p-multiselect-label-container, .p-treeselect-label-container { display: block; }
      |/* The comma-mode label, the drawer title, and the drawer content are plain
      |   blocks in Prime (kyo's div default is a column flexbox); the sheet's
      |   chip-mode label rule (0,2,0) keeps winning with display: flex. */
      |.p-multiselect-label, .p-drawer-title, .p-drawer-content { display: block; }
      |/* The chip wrapper is a plain inline span in Prime — an inline-flex/flex
      |   wrapper would make the chip a flex item and blockify its inline-flex. */
      |span.p-multiselect-chip-item { display: inline; }
      |/* Panel list/tree containers are blocks; Prime caps them via the
      |   scrollHeight prop as an inline style (multiselect default 14rem,
      |   treeselect 20rem) — expressed as CSS here. */
      |.p-multiselect-overlay .p-multiselect-list-container { display: block; max-height: 14rem; }
      |.p-treeselect-overlay .p-treeselect-tree-container { display: block; max-height: 20rem; }
      |.p-cascadeselect-overlay .p-cascadeselect-list-container { display: block; }
      |/* The nested cascade sub-panel rides the Overlay primitive; the sheet's
      |   `.p-cascadeselect-option-list { display: none }` targets Prime's
      |   JS-toggled nested ul — restore the open panel (0,2,0 beats 0,1,0) and
      |   kill the overlay gutter (nested panels sit flush: the sheet's
      |   inset-inline-start: 100%; inset-block-start: 0). */
      |.p-uic-overlay-panel.p-cascadeselect-option-list { display: block; margin: 0; }
      |/* An open cascade group row hosts its absolutely-positioned sub-panel;
      |   kyo's li default is a centered row flexbox — stack content full-width
      |   (the tree-node/menu-row lesson). */
      |li.p-cascadeselect-option { flex-direction: column; align-items: stretch; }
      |/* The multiselect/treeselect clear affordance is a real <button> (Prime
      |   uses a bare svg with handlers) — strip the native chrome; the extracted
      |   .p-*-clear-icon rules color it. */
      |button.p-multiselect-clear-icon { background: transparent; border: 0 none; padding: 0; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; }
      |button.p-multiselect-clear-icon svg { width: 100%; height: 100%; }
      |/* GlyphSvg spans sized by the extracted component CSS scale their inner
      |   svg (wave-L additions to the earlier lists). */
      |span.p-multiselect-dropdown-icon, span.p-cascadeselect-dropdown-icon,
      |span.p-treeselect-dropdown-icon, span.p-cascadeselect-group-icon {
      |  display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0;
      |}
      |span.p-multiselect-dropdown-icon > svg, span.p-cascadeselect-dropdown-icon > svg,
      |span.p-treeselect-dropdown-icon > svg, span.p-cascadeselect-group-icon > svg { width: 100%; height: 100%; }
      |/* Drawer: Prime positions the mask via DrawerStyle.inlineStyles —
      |   expressed as CSS here (the ToggleSwitch/Toast precedent). The mask
      |   shares the Dialog mask's z-index layer (1200 — Prime's modal layer). */
      |.p-drawer-mask { position: fixed; inset: 0; display: flex; flex-direction: row; z-index: 1200; }
      |.p-drawer-mask.p-drawer-left { justify-content: flex-start; align-items: center; }
      |.p-drawer-mask.p-drawer-right { justify-content: flex-end; align-items: center; }
      |.p-drawer-mask.p-drawer-top { justify-content: center; align-items: flex-start; }
      |.p-drawer-mask.p-drawer-bottom { justify-content: center; align-items: flex-end; }
      |.p-drawer-mask.p-drawer-full { justify-content: center; align-items: center; }
      |/* ==== wave M: ContextMenu / ToastService / ConfirmDialog ==== */
      |/* ContextMenu rows mirror the wave-K menu-family restorers: kyo's li
      |   default is a centered row flexbox — stack content full-width; the link
      |   restores the browser's row default. */
      |li.p-contextmenu-item { flex-direction: column; align-items: stretch; }
      |a.p-contextmenu-item-link { flex-direction: row; }
      |/* The root panel rides the Overlay primitive (display:block geometry) —
      |   the root list inside it is the sheet's flex column. Nested submenus sit
      |   flush against their row (the sheet's left:100%/top:0): kill the overlay
      |   gutter and restore the sheet's flex column over the panel's block. */
      |.p-uic-overlay-panel.p-contextmenu-submenu { display: flex; flex-direction: column; margin: 0; }
      |/* GlyphSvg span sized by the extracted contextmenu CSS scales its inner
      |   svg (wave-M addition to the earlier lists). */
      |span.p-contextmenu-submenu-icon { display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; }
      |span.p-contextmenu-submenu-icon > svg { width: 100%; height: 100%; }
      |/* ConfirmDialog content: the sheet declares display:flex without a
      |   direction and relies on the browser's row default — kyo's div column
      |   default must be restored to row. */
      |.p-confirmdialog .p-dialog-content { flex-direction: row; }
      |/* ConfirmDialog icon: the sheet sizes .p-confirmdialog-icon; the GlyphSvg
      |   span scales its inner svg with the token box. */
      |span.p-confirmdialog-icon { display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; }
      |span.p-confirmdialog-icon > svg { width: 100%; height: 100%; }
      |/* ==== wave N: InputNumber / Password / InputOtp / Slider / Knob ==== */
      |/* Row restorers (kyo base CSS: every div is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). The
      |   InputNumber root is a span (inline-flex row by default) and needs none. */
      |.p-password, .p-inputotp { flex-direction: row; }
      |/* InputNumber static adornments (kyo extension — Prime's in-value
      |   locale/currency formatting is keystroke-bound client JS and is
      |   deliberately not ported; see InputNumber.scala). */
      |.p-uic-inputnumber-prefix, .p-uic-inputnumber-suffix {
      |  display: inline-flex; align-items: center; padding-inline: 0.5rem;
      |  color: var(--p-text-muted-color); white-space: nowrap;
      |}
      |/* Password: the strength meter renders INLINE below the field (kyo
      |   deviation — Prime floats it in a while-typing overlay); the sheet's
      |   .p-password-content flex column applies, this adds the gap and a width
      |   tied to the field above. */
      |.p-uic-password-feedback { margin-block-start: 0.5rem; width: 100%; }
      |/* Password toggle icon: the sheet positions .p-password-toggle-mask-icon;
      |   the clickable span centers and scales its inner svg. */
      |span.p-password-toggle-mask-icon {
      |  display: inline-flex; align-items: center; justify-content: center; cursor: pointer;
      |}
      |span.p-password-toggle-mask-icon > svg { width: 100%; height: 100%; }
      |/* Slider: the interaction layer is a REAL invisible <input type=range>
      |   stretched over the Prime track divs (kyo extension) — native drag +
      |   keyboard for free, the visual fill/handle stay Prime's anatomy. The
      |   hit area is grown past the 3px track so the thumb stays grabbable. */
      |.p-uic-slider-native {
      |  position: absolute; opacity: 0; margin: 0; padding: 0;
      |  appearance: none; background: transparent; cursor: pointer;
      |}
      |.p-slider-horizontal > .p-uic-slider-native {
      |  left: 0; top: 50%; transform: translateY(-50%); width: 100%; height: 1.25rem;
      |}
      |.p-slider-vertical > .p-uic-slider-native {
      |  top: 0; left: 50%; transform: translateX(-50%); height: 100%; width: 1.25rem;
      |  writing-mode: vertical-lr; direction: rtl;
      |}
      |.p-slider.p-disabled > .p-uic-slider-native { cursor: default; }
      |/* PrimeVue positions range + handle via SliderStyle.inlineStyles — the
      |   extracted component CSS lacks it (the ToggleSwitch precedent). */
      |.p-slider-range, .p-slider-handle { position: absolute; }
      |/* Knob: kyo's div column default centers the dial; the sheet only styles
      |   the svg. inline-flex hugs the svg like Prime's inline root. */
      |.p-knob { display: inline-flex; }
      |/* ==== wave O: container/data block ==== */
      |/* Row restorers (kyo base CSS: every div/ul is a COLUMN flexbox; Prime never
      |   declares flex-direction and relies on the browser's row default). */
      |.p-orderlist, .p-picklist, .p-fileupload-basic-content, .p-terminal-prompt,
      |.p-galleria-items, .p-galleria-item, .p-galleria-thumbnail-items,
      |.p-galleria-thumbnail-item, ul.p-galleria-indicator-list,
      |.p-treetable-body-cell-content, .p-treetable-column-header-content { flex-direction: row; }
      |/* Terminal history rows are blocks in Prime: the prompt/value spans flow
      |   inline, the response div drops below. */
      |.p-terminal-command { display: block; }
      |/* Carousel items are blocks in Prime (kyo's div default is a column flexbox);
      |   the visible-window items carry Prime's inline flex-basis sizing. */
      |.p-carousel-item { display: block; }
      |/* Carousel slide: the runtime strip renders ALL items and is translated in
      |   place (bindStyleById) on a page turn — a kyo class carries the transition
      |   so it never fights Prime's own .p-carousel-item-list rules (which have no
      |   transform transition). The per-item flex-basis sizing stays inline. */
      |.p-uic-carousel-track { transition: transform .3s ease; }
      |/* FileUpload basic: the choose affordance is a real <label for> (native file
      |   dialog without JS) wearing Prime's Button classes — restore the row that
      |   kyo's label column default breaks. */
      |label.p-button { flex-direction: row; }
      |/* Galleria default templates: the preview image fills the stage, thumbnails
      |   stay small (Prime's showcase sizes both from the item templates). */
      |img.p-uic-galleria-image { width: 100%; display: block; }
      |img.p-uic-galleria-thumbnail-image { display: block; }
      |/* TreeTable: kyo-ui has no <thead>/<tbody> factories, so the thead/tbody-
      |   scoped Prime rules are re-expressed against the stamped row classes
      |   (.p-uic-tt-header-row / .p-uic-tt-row — the DataTable precedent). */
      |.p-treetable-table tr.p-uic-tt-row {
      |  outline-color: transparent;
      |  background: var(--p-treetable-row-background); color: var(--p-treetable-row-color);
      |}
      |.p-treetable-table tr.p-uic-tt-row > td {
      |  text-align: start; padding: var(--p-treetable-body-cell-padding);
      |  border-color: var(--p-treetable-body-cell-border-color); border-style: solid; border-width: 0 0 1px 0;
      |}
      |.p-treetable-hoverable tr.p-uic-tt-row:not(.p-treetable-row-selected):hover {
      |  background: var(--p-treetable-row-hover-background); color: var(--p-treetable-row-hover-color);
      |}
      |.p-treetable-table tr.p-treetable-row-selected {
      |  background: var(--p-treetable-row-selected-background); color: var(--p-treetable-row-selected-color);
      |}
      |.p-treetable-table tr.p-treetable-row-selected > td {
      |  border-block-end-color: var(--p-treetable-body-cell-selected-border-color);
      |}
      |.p-treetable-gridlines th.p-treetable-header-cell { border-width: 1px 0 1px 1px; }
      |.p-treetable-gridlines th.p-treetable-header-cell:last-child { border-width: 1px; }
      |.p-treetable-gridlines .p-treetable-table tr > td { border-width: 0 0 1px 1px; }
      |.p-treetable-gridlines .p-treetable-table tr > td:last-child { border-width: 0 1px 1px 1px; }
      |.p-treetable-sm th.p-treetable-header-cell { padding: 0.375rem 0.5rem; }
      |.p-treetable-sm .p-treetable-table tr > td { padding: 0.375rem 0.5rem; }
      |.p-treetable-lg th.p-treetable-header-cell { padding: 0.9375rem 1.25rem; }
      |.p-treetable-lg .p-treetable-table tr > td { padding: 0.9375rem 1.25rem; }
      |.p-treetable-table tr.p-treetable-empty-message > td { text-align: center; color: var(--p-text-muted-color); }
      |/* PrimeVue scrolls the container via TreeTableStyle.inlineStyles — expressed
      |   as CSS here (the ToggleSwitch precedent). */
      |.p-treetable-table-container { overflow: auto; }
      |/* Leaf togglers keep their box but hide — Prime's inline visibility style. */
      |.p-uic-tt-toggle-hidden { visibility: hidden; }
      |/* OrgChart: collapsed subtrees keep their rows and hide via visibility —
      |   Prime's inline childStyle. */
      |.p-uic-oc-hidden { visibility: hidden; }
      |/* OrgChart: no <tbody> factory — the tbody-scoped cell rule re-expressed
      |   (nested tables make the descendant selector equivalent to Prime's
      |   per-table child chain). */
      |.p-organizationchart-table td {
      |  text-align: center; vertical-align: top; padding: 0 var(--p-organizationchart-gutter);
      |}
      |/* GlyphSvg spans sized by the extracted component CSS scale their inner svg
      |   (wave-O additions to the earlier lists). */
      |span.p-galleria-prev-icon, span.p-galleria-next-icon,
      |span.p-galleria-thumbnail-prev-icon, span.p-galleria-thumbnail-next-icon,
      |span.p-treetable-sort-icon, span.p-treetable-node-toggle-icon {
      |  display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0;
      |}
      |span.p-galleria-prev-icon > svg, span.p-galleria-next-icon > svg,
      |span.p-galleria-thumbnail-prev-icon > svg, span.p-galleria-thumbnail-next-icon > svg,
      |span.p-treetable-sort-icon > svg, span.p-treetable-node-toggle-icon > svg { width: 100%; height: 100%; }
      |/* ==== wave R: ColorPicker / VirtualScroller ==== */
      |/* ColorPicker drag: the STABLE surface elements (.p-colorpicker-color-selector /
      |   .p-colorpicker-hue) carry the pointer handlers and define the coordinate
      |   rect; the reactive tint/handle inside them must NOT intercept the pointer
      |   (a per-frame re-render would otherwise detach the captured target and the
      |   payload rect would be the wrong element's). So the handles, the tint
      |   background, AND the reactive wrapper spans are pointer-transparent — the
      |   pointer always lands on the stable surface. */
      |.p-colorpicker-color-handle, .p-colorpicker-hue-handle,
      |.p-colorpicker-color-background { pointer-events: none; }
      |.p-colorpicker-color-selector > span[data-kyo-reactive],
      |.p-colorpicker-hue > span[data-kyo-reactive] { pointer-events: none; display: contents; }
      |/* Overlay-mode panel: the Overlay primitive floats the panel; the
      |   .p-colorpicker-panel skin (sheet: position:absolute; top:0; left:0) must
      |   flow STATICALLY inside it rather than re-anchor to the panel origin. */
      |.p-uic-overlay-panel .p-colorpicker-panel { position: static; }
      |/* ---- enter/leave transitions (Welle P) ----
      |   The fork's LEAVE ghost keeps the leave class until animation/transitionend,
      |   so Prime's own keyframe -leave-active classes (from the extracted sheets)
      |   drive the exit animations verbatim. The fork's ENTER seeds a class, forces
      |   reflow, then releases it next frame — a FROM-STATE + transition model, which
      |   Prime's animation-based enter keyframes do NOT fit; so enter rides small
      |   from-state classes below whose base element carries a transition, mirroring
      |   the start state of Prime's enter keyframes. */
      |.p-uic-enter-fade { opacity: 0; }
      |.p-uic-enter-scale { opacity: 0; transform: scale(0.92); }
      |.p-uic-leave-fade { opacity: 0; }
      |/* Directional slide ENTER from-states (shared: Drawer panel, Toast message).
      |   The fork adds the class on insert, forces reflow, releases it next frame; the
      |   target's own `transition: transform` (the Drawer sheet / the .p-toast-message
      |   rule below) then animates from this edge to rest. Space-join with
      |   p-uic-enter-fade for a slide+fade. */
      |.p-uic-slide-enter-left { transform: translate3d(-100%, 0, 0); }
      |.p-uic-slide-enter-right { transform: translate3d(100%, 0, 0); }
      |.p-uic-slide-enter-top { transform: translate3d(0, -100%, 0); }
      |.p-uic-slide-enter-bottom { transform: translate3d(0, 100%, 0); }
      |.p-overlay-mask { transition: opacity 150ms ease; }
      |.p-dialog { transition: opacity 150ms ease, transform 200ms cubic-bezier(.19,1,.22,1); }
      |.p-toast-message { transition: opacity 200ms ease, transform 300ms ease; }
      |.p-message { transition: opacity 250ms ease; }
      |.p-uic-overlay-panel { transition: opacity 120ms ease, transform 120ms ease; }
      |/* Drawer LEAVE slide: the mask leave ghost keeps `p-overlay-mask-leave-active`
      |   until its keyframe ends; while it fades, the cloned panel slides back out its
      |   docking edge via the sheet's own `.p-drawer { transition: transform 0.3s }`,
      |   keyed on the position token so each edge exits the way it entered (Full has
      |   transition:none in the sheet, so it stays a fade). */
      |.p-drawer-mask.p-drawer-left.p-overlay-mask-leave-active .p-drawer { transform: translate3d(-100%, 0, 0); }
      |.p-drawer-mask.p-drawer-right.p-overlay-mask-leave-active .p-drawer { transform: translate3d(100%, 0, 0); }
      |.p-drawer-mask.p-drawer-top.p-overlay-mask-leave-active .p-drawer { transform: translate3d(0, -100%, 0); }
      |.p-drawer-mask.p-drawer-bottom.p-overlay-mask-leave-active .p-drawer { transform: translate3d(0, 100%, 0); }
      |/* Stepper panel crossfade (mounted+keyed on the active step): the incoming panel
      |   enters with p-uic-enter-fade and the outgoing leave ghost fades via
      |   p-uic-leave-fade — both ride this opacity transition. */
      |.p-uic-steppanel-anim { transition: opacity 0.2s ease; }
      |/* ---- toggleable container collapse (#7, mounted8 in-place class toggle) ----
      |   The Fieldset/Panel/Accordion content containers already come out of the
      |   extracted sheet as display:grid;grid-template-rows:1fr (Prime's own collapse
      |   anatomy: container = grid, wrapper = the single row). .p-uic-collapse adds the
      |   grid-rows transition; .p-uic-collapsed animates the row to 0fr. The class is
      |   toggled IN PLACE (bindClassById, so the element is never replaced and the
      |   transition fires — an outerHTML swap would reset it). overflow:hidden clips
      |   the row as it closes; the inner padding rides along. The 0,2,0 collapsed rule
      |   wins over the sheet's 0,1,0 container rule (source order also favors it). */
      |.p-uic-collapse { display: grid; grid-template-rows: 1fr; transition: grid-template-rows 0.2s ease; }
      |.p-uic-collapse.p-uic-collapsed { grid-template-rows: 0fr; }
      |.p-uic-collapse > * { overflow: hidden; min-height: 0; }
      |/* ---- draggable / resizable Dialog (Welle R2, mounted6 pointer-drag) ----
      |   The movable box drops the transform transition so the live drag translate
      |   never smears; the header is the drag surface, a bottom-right handle resizes. */
      |/* Knob drag surface: the svg dial is pointer-events:none so the drag pointer
      |   lands on the stable outer .p-knob div whose rect is the dial coordinate space. */
      |.p-knob { touch-action: none; }
      |.p-uic-knob-dial { pointer-events: none; }
      |.p-uic-dialog-movable { transition: none; position: relative; }
      |.p-uic-dialog-draggable-header { cursor: move; user-select: none; touch-action: none; }
      |.p-uic-dialog-resize-handle { position: absolute; right: 2px; bottom: 2px; width: 16px; height: 16px; cursor: nwse-resize; touch-action: none; opacity: .5; background: linear-gradient(135deg, transparent 50%, var(--p-dialog-color, currentColor) 50%, var(--p-dialog-color, currentColor) 60%, transparent 60%, transparent 70%, var(--p-dialog-color, currentColor) 70%, var(--p-dialog-color, currentColor) 80%, transparent 80%); }
      |/* ---- VirtualScroller native scroll (onScrollPosition) ----
      |   The viewport scrolls natively; overscroll-behavior:contain stops the wheel/trackpad from chaining to the
      |   page at the list's edge. Each windowed row is absolutely positioned at top:i·itemSize inside the
      |   full-height spacer, so the browser's scrollbar spans all rows while only the window is in the DOM. */
      |.p-uic-vs-viewport { overflow: auto; overscroll-behavior: contain; }
      |.p-uic-vs-item { position: absolute; left: 0; right: 0; overflow: hidden; }
      |""".stripMargin
            + textClampCss
            + dialogSeverityCss

    /** Line-clamp rules behind [[Text.maxLines]] (`data-uic-max-lines`, 1–10). */
    private def textClampCss: String =
        (1 to 10)
            .map(n => s""".p-uic-text--clamp[data-uic-max-lines="$n"] { -webkit-line-clamp: $n; }""")
            .mkString("", "\n", "\n")

    /** Dialog severity accents (`Dialog.severity`, kyo extension): a subtle colored
      * border under the header plus a tinted leading icon, keyed on the button
      * background token of each severity.
      */
    private def dialogSeverityCss: String =
        Severity.values
            .map { s =>
                val t = s.token
                s""".p-uic-dialog-$t .p-dialog-header { border-block-end: 2px solid var(--p-button-$t-background); }
           |.p-uic-dialog-$t .p-uic-dialog-severity-icon { color: var(--p-button-$t-background); }""".stripMargin
            }
            .mkString("", "\n", "\n")

    /** Complete page CSS. Drop into `PageHead.css` or a `<style>` tag. */
    def css(using Frame): String = primeCss
end Theme
