package kyo.apollo.codegen

import caliban.parsing.adt.Document
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import scala.jdk.CollectionConverters.*
import scala.util.Using

/** Build-time driver that ties the codegen pieces together: it loads a schema
  * (via [[SchemaLoader]]), runs [[ApolloClientWriter]] over it, and writes the
  * emitted Scala sources to disk.
  *
  * The in-repo `apolloGenerate` sbt task (build.sbt) runs [[main]] through the
  * `kyo-apollo-codegen` project's `runner` over its classpath and adds the output
  * to a project's `Compile / sourceGenerators`; the options are named (see
  * [[main]]).
  *
  * The pure [[generate]] helper (no filesystem access) is exposed so tests can
  * assert on the emitted source set directly, and [[run]] performs the load →
  * emit → write pipeline idempotently (a file is only rewritten when its bytes
  * change, so regeneration on every compile does not churn timestamps and force
  * needless recompiles).
  */
object CodegenRunner:

    /** The generator's command line, parsed. */
    final case class Options(
        schema: Path,
        out: Path,
        packageName: String,
        scalarMappings: Map[String, String],
        clientFields: List[ClientFieldDecl]
    ):
        def config: CodegenConfig = CodegenConfig(packageName, scalarMappings, clientFields)
    end Options

    /** The marker line every generated source carries; [[run]] only ever deletes
      * files that contain it.
      */
    private val GeneratedMarker = "// GENERATED by apollo-codegen"

    /** Every generated source for `schema`: the shared schema types (enums, input
      * objects, and the custom-scalar registry), then the inline-query selector layer
      * (one selector object per schema object type plus the
      * `Queries`/`Mutations`/`Subscriptions` roots). Purely schema-driven — no
      * operation documents, no I/O.
      */
    def generate(schema: Document, config: CodegenConfig): List[GeneratedSource] =
        ApolloClientWriter.writeSchemaTypes(schema, config) ++
            ApolloClientWriter.writeSelectors(schema, config) ++
            ApolloClientWriter.writeClientFields(schema, config) ++
            ApolloClientWriter.writeSchemaIdentities(schema, config)

    /** Load the schema from disk, emit the sources, and write them into `outputDir`
      * (created if absent). Returns the paths of the emitted sources, in emission
      * order. A source whose on-disk bytes are already identical is left untouched,
      * and a generated source this run no longer emits (its type left the schema) is
      * deleted; files without the generator's marker line are never touched.
      *
      * @throws CodegenException on any parse/emit/type-resolution failure.
      */
    def run(
        schemaPath: Path,
        outputDir: Path,
        config: CodegenConfig
    ): List[Path] =
        val schema  = SchemaLoader.fromFile(schemaPath)
        val sources = generate(schema, config)
        Files.createDirectories(outputDir)
        val written = sources.map(src => writeIfChanged(outputDir.resolve(src.fileName), src.contents))
        pruneStale(outputDir, written.toSet)
        written
    end run

    /** Write `contents` to `target` only when it differs from what is already
      * there, so unchanged regenerations keep a stable modification time.
      */
    private def writeIfChanged(target: Path, contents: String): Path =
        val bytes = contents.getBytes("UTF-8")
        val unchanged =
            Files.exists(target) && java.util.Arrays.equals(Files.readAllBytes(target), bytes)
        if !unchanged then Files.write(target, bytes): Unit
        target
    end writeIfChanged

    /** Delete the generated `.scala` files directly in `outputDir` that are not in `keep`. */
    private def pruneStale(outputDir: Path, keep: Set[Path]): Unit =
        Using.resource(Files.list(outputDir)) { entries =>
            entries.iterator.asScala
                .filter(p => p.toString.endsWith(".scala") && !keep.contains(p) && Files.isRegularFile(p))
                .filter(p => Files.readString(p).contains(GeneratedMarker))
                .foreach(Files.delete)
        }

    /** Command-line entry point, run by the `apolloGenerate` sbt task:
      *
      * {{{
      * --schema <file>                          GraphQL schema SDL (required)
      * --out <dir>                              directory the sources are written to (required)
      * --package <name>                         package the sources declare (required)
      * --scalar <Name=fully.qualified.Type>     map a custom scalar (repeatable)
      * --client-field <Type.field: T = default> declare a local @client field (repeatable)
      * }}}
      *
      * Operations are written inline against the generated selectors
      * (`Queries.country(code)(Country.name).toQuery()`), so there are no operation
      * documents to pass.
      *
      * @throws CodegenException for a malformed command line or any generation failure;
      *   run in a forked JVM, that is one line on stderr and a non-zero exit.
      */
    def main(args: Array[String]): Unit =
        val options = parseArgs(args.toList)
        val written = run(options.schema, options.out, options.config)
        written.foreach(path => println(s"[apollo-codegen] wrote $path"))
    end main

    /** Parse the named options of [[main]]. */
    private[codegen] def parseArgs(args: List[String]): Options =
        final case class Acc(
            single: Map[String, String] = Map.empty,
            scalars: List[String] = Nil,
            clientFields: List[String] = Nil
        )
        val Single = Set("--schema", "--out", "--package")
        @annotation.tailrec
        def loop(rest: List[String], acc: Acc): Acc =
            rest match
                case Nil => acc
                case name :: tail if Single(name) || name == "--scalar" || name == "--client-field" =>
                    tail match
                        case Nil => throw CodegenException.MissingValue(name)
                        case value :: next =>
                            if name == "--scalar" then loop(next, acc.copy(scalars = value :: acc.scalars))
                            else if name == "--client-field" then
                                loop(next, acc.copy(clientFields = value :: acc.clientFields))
                            else if acc.single.contains(name) then throw CodegenException.RepeatedOption(name)
                            else loop(next, acc.copy(single = acc.single.updated(name, value)))
                case other :: _ => throw CodegenException.UnknownOption(other)
        val acc = loop(args, Acc())
        def required(name: String): String =
            acc.single.getOrElse(name, throw CodegenException.MissingOption(name))
        Options(
            schema = Paths.get(required("--schema")),
            out = Paths.get(required("--out")),
            packageName = required("--package"),
            scalarMappings = acc.scalars.reverse.map(parseScalarMapping).toMap,
            clientFields = acc.clientFields.reverse.map(ClientFieldDecl.parse)
        )
    end parseArgs

    /** Parse one `Name=fully.qualified.Type` scalar mapping. */
    private[codegen] def parseScalarMapping(entry: String): (String, String) =
        entry.split("=", 2) match
            case Array(name, tpe) if name.trim.nonEmpty && tpe.trim.nonEmpty => name.trim -> tpe.trim
            case _                                                           => throw CodegenException.MalformedScalarMapping(entry)
end CodegenRunner
